# -*- coding: utf-8 -*-
"""Tic-Tac-Toe-Computer-vs-User.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PzjHoQOKKuAhHF3WdDtYoqCpb8oMaubD
"""

import random


def display_board(board_list):
    print(" {} | {} | {} ".format(board_list[0],board_list[1],board_list[2]))
    print("-----------")
    print(" {} | {} | {} ".format(board_list[3],board_list[4],board_list[5]))
    print("-----------")
    print(" {} | {} | {} ".format(board_list[6],board_list[7],board_list[8]))

available = [num for num in range(1,10)]
display_board(available)

player_one = input('First player enter your name. ')

def make_mark(emoj, message, str):
    if str == 'user':
        user_name = int(input(message))
        if user_name not in matrix:
            print('💀The 💀 place 💀is 💀ocopied.💀')
            display_board(matrix)
            return False

        else:
            index = matrix.index(user_name)
            matrix[index] = emoj

            return matrix
    else:
        user_name = random.choice(matrix)
        print(f'Computer choos {user_name}.')
        if user_name not in matrix:
            print('💀The 💀 place 💀is 💀ocopied.💀')
            display_board(matrix)
            return False

        else:
            index = matrix.index(user_name)
            matrix[index] = emoj

            return matrix

def check_for_win():
    if (matrix[0]== '💚' and matrix[1]=='💚' and matrix[2]=='💚') or (matrix[0]== '💚' and matrix[4]=='💚' and matrix[8]=='💚'):
        return True
    elif (matrix[0]== '💚' and matrix[3]=='💚' and matrix[6]=='💚') or (matrix[6]== '💚' and matrix[4]=='💚' and matrix[2]=='💚'):
        return True
    elif (matrix[1]== '💚' and matrix[4]=='💚' and matrix[7]=='💚') or (matrix[6]== '💚' and matrix[7]=='💚' and matrix[8]=='💚'):
        return True
    elif (matrix[2]== '💚' and matrix[5]=='💚' and matrix[8]=='💚') or (matrix[3]== '💚' and matrix[4]=='💚' and matrix[5]=='💚'):
        return True

    elif (matrix[0] == '💙' and matrix[1] == '💙' and matrix[2] == '💙') or (matrix[0] == '💙' and matrix[4] == '💙' and matrix[8] == '💙'):
        return True
    elif (matrix[0] == '💙' and matrix[3] == '💙' and matrix[6] == '💙') or (matrix[6] == '💙' and matrix[4] == '💙' and matrix[2] == '💙'):
        return True
    elif (matrix[1] == '💙' and matrix[4] == '💙' and matrix[7] == '💙') or (matrix[6] == '💙' and matrix[7] == '💙' and matrix[8] == '💙'):
        return True
    elif (matrix[2] == '💙' and matrix[5] == '💙' and matrix[8] == '💙') or (matrix[3] == '💙' and matrix[4] == '💙' and matrix[5] == '💙'):
        return True
    else:
        return False


matrix = [1, 2, 3, 4, 5, 6, 7, 8, 9]


def is_continue():

    is_game_on = True
    count = 9
    while is_game_on:
        result = make_mark('💚', f'{player_one} input chose your number. ', 'user')
        while result == False:
            result = make_mark('💚', f'Player_one input chose your number. ', 'user')
        else:
            display_board(matrix)
            count -= 1

            if check_for_win() == True:
                print(f'Congratulations {player_one} you win the game 🎉🎉🎉🎉')
                break

            if count == 0:
                print('The game is Tie')
                break
        print('\n')
        result = make_mark('💙',f'Computer choose a number. ', 'com')
        while result == False:
            result = make_mark('💙', f'Computer choose a number. ', 'com')
        else:
            display_board(matrix)
            count -= 1
            if check_for_win() == True:
                print(f"Computer is winer of the game")

                break
            if count == 0:
                print('The game is tie')
                break

    game_continue = input("Do you want to play agin? say y for yes and n for No. ")
    if game_continue == 'y':
        is_continue()

    else:
        game_continue = False

is_continue()